version: "3.11"

services:
  web:
    build: .
    command: uvicorn main:app --host=0.0.0.0 --port=5910
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5910:5910"
